version: "3.8"

services:
  timecraft-db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timecraft
      POSTGRES_DB: timecraft
      POSTGRES_PASSWORD: timecraft
    volumes:
      - timecraft-db-vol:/var/lib/postgresql/data.liku

volumes:
  timecraft-db-vol: